
package photo.ws.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PhotoWSService", targetNamespace = "http://session.photo/", wsdlLocation = "http://localhost:8080/PhotoWSService/PhotoWS?wsdl")
public class PhotoWSService
    extends Service
{

    private final static URL PHOTOWSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/PhotoWSService/PhotoWS?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PHOTOWSSERVICE_WSDL_LOCATION = url;
    }

    public PhotoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhotoWSService() {
        super(PHOTOWSSERVICE_WSDL_LOCATION, new QName("http://session.photo/", "PhotoWSService"));
    }

    /**
     * 
     * @return
     *     returns PhotoWS
     */
    @WebEndpoint(name = "PhotoWSPort")
    public PhotoWS getPhotoWSPort() {
        return (PhotoWS)super.getPort(new QName("http://session.photo/", "PhotoWSPort"), PhotoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhotoWS
     */
    @WebEndpoint(name = "PhotoWSPort")
    public PhotoWS getPhotoWSPort(WebServiceFeature... features) {
        return (PhotoWS)super.getPort(new QName("http://session.photo/", "PhotoWSPort"), PhotoWS.class, features);
    }

}
